server.port=18080
server.address=127.0.0.1

spring.application.name=Diary Desktop Application

spring.datasource.url=jdbc:sqlite:./data/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.liquibase.enabled=false

jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

google.api.client-id=${GOOGLE_CLIENT_ID}
google.api.client-secret=${GOOGLE_CLIENT_SECRET}
google.api.refresh-token=${GOOGLE_REFRESH_TOKEN}
app.gmail.sender=${GOOGLE_GMAIL_SENDER}

app.base-url=http://127.0.0.1:18080

app.admin.database.clear.enabled=false

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}
telegram.bot.name=${TELEGRAM_BOT_NAME}

app.cors.allowed-origin=*