# Google Login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile

# Gmail API
google.api.client-id=${GOOGLE_CLIENT_ID:}
google.api.client-secret=${GOOGLE_CLIENT_SECRET:}
google.api.refresh-token=${GOOGLE_REFRESH_TOKEN:}
app.gmail.sender=${GOOGLE_GMAIL_SENDER:no-reply@example.local}

# Base Url
app.base-url=${APP_BASE_URL:http://localhost}

# Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.chat.id=${TELEGRAM_CHAT_ID:}
telegram.bot.name=${TELEGRAM_BOT_NAME:}

# CORS
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:*}
