server.port=18080
server.address=127.0.0.1

spring.application.name=Diary Desktop Application

spring.datasource.url=jdbc:sqlite:${APP_DB_PATH}
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.properties.hibernate.default_batch_fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.liquibase.enabled=false

jwt.secret=desktop-super-secret-key-for-jwt-very-long-123456789
jwt.access-expiration-ms=3600000
jwt.refresh-expiration-ms=604800000

app.base-url=http://127.0.0.1:18080

app.admin.database.clear.enabled=true

app.cors.allowed-origin=*